/**
 * PanguPay Service Worker
 * 
 * Provides offline support and caching for the application:
 * - Static asset caching (Cache-First for CSS, images)
 * - Network-First for API calls
 * - Network-Only for development resources (Vite HMR)
 * - Offline fallback page
 */

// Cache version - update this when assets change
const CACHE_VERSION = 'v1.0.1';
const CACHE_NAME = `pangupay-${CACHE_VERSION}`;

// Static assets to cache on install (only stable assets)
const STATIC_ASSETS = [
  '/',
  '/index.html',
  '/assets/logo.png',
  '/assets/logo2.png',
  '/assets/logo3.png',
  '/assets/avatar.png'
];

// CSS files to cache (separate for easier management)
const CSS_ASSETS = [
  '/css/base.css',
  '/css/animations.css',
  '/css/utilities.css',
  '/css/components.css',
  '/css/header.css',
  '/css/welcome.css',
  '/css/toast.css',
  '/css/entry.css',
  '/css/new-user.css',
  '/css/login.css',
  '/css/wallet.css',
  '/css/transaction.css',
  '/css/import-wallet.css',
  '/css/join-group.css',
  '/css/group.css',
  '/css/inquiry.css',
  '/css/profile.css',
  '/css/main-v2.css',
  '/css/history.css',
  '/css/footer.css',
  '/css/energy-saving.css',
  '/css/wallet_struct_styles.css',
  '/css/p2-improvements.css'
];

// Patterns for requests that should NEVER be cached (development/dynamic)
const NEVER_CACHE_PATTERNS = [
  /\?t=\d+/,           // Vite cache-busted requests
  /\.hot-update\./,    // Vite HMR updates
  /@vite/,             // Vite internal
  /@fs/,               // Vite file system
  /node_modules/,      // Node modules
  /ws:/,               // WebSocket
  /sockjs/,            // SockJS
];

// API paths that should use network-first strategy
const API_PATHS = ['/api/'];

// ========================================
// Install Event
// ========================================

self.addEventListener('install', (event) => {
  // Silent install - no console logs in production
  
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => {
        // Cache static assets, but don't fail if some don't exist
        const allAssets = [...STATIC_ASSETS, ...CSS_ASSETS];
        return Promise.allSettled(
          allAssets.map(url => 
            cache.add(url).catch(() => {
              // Silently ignore cache failures
            })
          )
        );
      })
      .then(() => {
        // Skip waiting to activate immediately
        return self.skipWaiting();
      })
      .catch(() => {
        // Silently fail - SW is optional
      })
  );
});

// ========================================
// Activate Event
// ========================================

self.addEventListener('activate', (event) => {
  // Silent activation
  
  event.waitUntil(
    // Clean up old caches
    caches.keys()
      .then((cacheNames) => {
        return Promise.all(
          cacheNames
            .filter(name => name.startsWith('pangupay-') && name !== CACHE_NAME)
            .map(name => caches.delete(name))
        );
      })
      .then(() => {
        // Take control of all clients immediately
        return self.clients.claim();
      })
      .catch(() => {
        // Silently fail
      })
  );
});

// ========================================
// Fetch Event
// ========================================

self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);
  
  // Skip non-GET requests
  if (request.method !== 'GET') {
    return;
  }
  
  // Skip cross-origin requests
  if (url.origin !== location.origin) {
    return;
  }
  
  // Skip requests that should never be cached (Vite dev, HMR, etc.)
  const fullUrl = request.url;
  if (NEVER_CACHE_PATTERNS.some(pattern => pattern.test(fullUrl))) {
    // Let these requests go directly to network without SW intervention
    return;
  }
  
  // Check if this is an API request
  const isApiRequest = API_PATHS.some(path => url.pathname.startsWith(path));
  
  // Check if this is a JS file (may be dynamically generated by Vite)
  const isJsFile = url.pathname.endsWith('.js') || url.pathname.endsWith('.ts');
  
  if (isApiRequest) {
    // Network-first for API requests
    event.respondWith(networkFirst(request));
  } else if (isJsFile) {
    // Network-first for JS files (they may change during development)
    event.respondWith(networkFirstSilent(request));
  } else {
    // Cache-first for static assets (CSS, images, HTML)
    event.respondWith(cacheFirstSilent(request));
  }
});

// ========================================
// Caching Strategies
// ========================================

/**
 * Cache-first strategy (silent version - no errors thrown)
 * Good for static assets that don't change often
 */
async function cacheFirstSilent(request) {
  try {
    const cachedResponse = await caches.match(request);
    
    if (cachedResponse) {
      // Return cached response and update cache in background (silently)
      updateCacheSilent(request);
      return cachedResponse;
    }
    
    // If not in cache, fetch from network
    const networkResponse = await fetch(request);
    
    // Cache the response if successful
    if (networkResponse && networkResponse.ok) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, networkResponse.clone()).catch(() => {});
    }
    
    return networkResponse;
  } catch (error) {
    // Return offline fallback for navigation requests
    if (request.mode === 'navigate') {
      const fallback = await caches.match('/index.html');
      if (fallback) return fallback;
    }
    
    // Return a minimal error response instead of throwing
    return new Response('', { status: 503, statusText: 'Service Unavailable' });
  }
}

/**
 * Network-first strategy (silent version)
 * Good for JS files and dynamic content
 */
async function networkFirstSilent(request) {
  try {
    const networkResponse = await fetch(request);
    
    // Cache successful responses for offline use
    if (networkResponse && networkResponse.ok) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, networkResponse.clone()).catch(() => {});
    }
    
    return networkResponse;
  } catch (error) {
    // Try cache as fallback
    const cachedResponse = await caches.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }
    
    // Return minimal error response
    return new Response('', { status: 503, statusText: 'Service Unavailable' });
  }
}

/**
 * Network-first strategy for API calls
 * Returns JSON error for offline state
 */
async function networkFirst(request) {
  try {
    const networkResponse = await fetch(request);
    return networkResponse;
  } catch (error) {
    // Try cache as fallback
    const cachedResponse = await caches.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }
    
    // Return JSON error response for API calls
    return new Response(JSON.stringify({
      error: 'Network unavailable',
      offline: true
    }), {
      status: 503,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}

/**
 * Legacy cache-first (for backward compatibility)
 */
async function cacheFirst(request) {
  return cacheFirstSilent(request);
}

/**
 * Stale-while-revalidate strategy
 * Returns cached response immediately, then updates cache in background
 */
async function staleWhileRevalidate(request) {
  const cachedResponse = await caches.match(request);
  
  const fetchPromise = fetch(request)
    .then(networkResponse => {
      if (networkResponse && networkResponse.ok) {
        caches.open(CACHE_NAME)
          .then(cache => cache.put(request, networkResponse.clone()))
          .catch(() => {});
      }
      return networkResponse;
    })
    .catch(() => cachedResponse);
  
  return cachedResponse || fetchPromise;
}

/**
 * Update cache in background (silent - never throws)
 */
async function updateCacheSilent(request) {
  try {
    const networkResponse = await fetch(request);
    
    if (networkResponse && networkResponse.ok) {
      const cache = await caches.open(CACHE_NAME);
      await cache.put(request, networkResponse);
    }
  } catch (error) {
    // Silently fail - cache update is not critical
  }
}

/**
 * Legacy updateCache (for backward compatibility)
 */
async function updateCache(request) {
  return updateCacheSilent(request);
}

// ========================================
// Message Handling
// ========================================

self.addEventListener('message', (event) => {
  const { type, payload } = event.data || {};
  
  switch (type) {
    case 'SKIP_WAITING':
      self.skipWaiting();
      break;
      
    case 'GET_VERSION':
      event.ports[0]?.postMessage({ version: CACHE_VERSION });
      break;
      
    case 'CLEAR_CACHE':
      caches.delete(CACHE_NAME).then(() => {
        event.ports[0]?.postMessage({ success: true });
      });
      break;
      
    case 'CACHE_URLS':
      if (payload?.urls) {
        caches.open(CACHE_NAME).then(cache => {
          return cache.addAll(payload.urls);
        }).then(() => {
          event.ports[0]?.postMessage({ success: true });
        });
      }
      break;
  }
});

// ========================================
// Background Sync (if supported)
// ========================================

self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-pending-transactions') {
    event.waitUntil(syncPendingTransactions());
  }
});

/**
 * Sync pending transactions when back online
 */
async function syncPendingTransactions() {
  // This would be implemented to sync any transactions
  // that were made while offline
  // Silent mode - no console output
}

// ========================================
// Push Notifications (if needed)
// ========================================

self.addEventListener('push', (event) => {
  if (!event.data) return;
  
  const data = event.data.json();
  
  const options = {
    body: data.body || '',
    icon: '/assets/logo.png',
    badge: '/assets/logo.png',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/'
    }
  };
  
  event.waitUntil(
    self.registration.showNotification(data.title || 'PanguPay', options)
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  const url = event.notification.data?.url || '/';
  
  event.waitUntil(
    clients.matchAll({ type: 'window' })
      .then(windowClients => {
        // Focus existing window if available
        for (const client of windowClients) {
          if (client.url === url && 'focus' in client) {
            return client.focus();
          }
        }
        // Otherwise open new window
        if (clients.openWindow) {
          return clients.openWindow(url);
        }
      })
  );
});

// Service worker loaded - silent mode
